### ISSUE TITLE
Implement Shunting Yard Algorithm

### ISSUE THREAD

**Issue by rsdexter** [rpi-alpaca/logic#2]
Implement the Shunting Yard Algorithm to parse statements, replacing the current recursive algorithm found in Tree.cpp. More info about the algorithm can be found on the [wiki page](https://github.com/rpi-alpaca/logic/wiki/Shunting-Yard-Algorithm).

**Comment by tobiasjpark** [comment]
Not sure if this will help you guys at all or not, but just in case - Aris from Bram-Hub contains deprecated code for converting expressions to Polish notation that could possibly be used as a reference/refactored into ALPACA? https://github.com/rpi-alpaca/logic/wiki/Aris . Again, I don't know exactly what you guys are doing so it may not be useful, but I thought it would be good to mention in case.

**Comment by venkatrsrinivas** [comment]
Hello Everyone. 
Currently, the Shunting Yard Algorithm has been merged into Master Branch.
Thank you.
